// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Proyect.Models;

#nullable disable

namespace Proyect.Migrations
{
    [DbContext(typeof(ProyectContext))]
    partial class ProyectContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Proyect.Models.Abono", b =>
                {
                    b.Property<int>("IdAbono")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdAbono"));

                    b.Property<bool>("Anulado")
                        .HasColumnType("bit");

                    b.Property<byte[]>("Comprobante")
                        .HasColumnType("varbinary(max)");

                    b.Property<DateTime>("FechaAbono")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<int>("IdReserva")
                        .HasColumnType("int");

                    b.Property<decimal>("Pendiente")
                        .HasColumnType("decimal(10, 2)");

                    b.Property<decimal>("Porcentaje")
                        .HasColumnType("decimal(5, 2)");

                    b.Property<decimal>("ValorAbono")
                        .HasColumnType("decimal(10, 2)");

                    b.Property<decimal>("Valordeuda")
                        .HasColumnType("decimal(10, 2)");

                    b.HasKey("IdAbono")
                        .HasName("PK__Abonos__A4693DA7FFF9E5A1");

                    b.HasIndex("IdReserva");

                    b.ToTable("Abonos");
                });

            modelBuilder.Entity("Proyect.Models.Cliente", b =>
                {
                    b.Property<int>("IdCliente")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdCliente"));

                    b.Property<string>("Apellido")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("Celular")
                        .HasMaxLength(15)
                        .IsUnicode(false)
                        .HasColumnType("varchar(15)");

                    b.Property<string>("CorreoElectronico")
                        .IsRequired()
                        .HasMaxLength(150)
                        .IsUnicode(false)
                        .HasColumnType("varchar(150)");

                    b.Property<string>("Direccion")
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("Documento")
                        .IsRequired()
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)");

                    b.Property<bool>("Estado")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("TipoDocumento")
                        .IsRequired()
                        .HasMaxLength(10)
                        .IsUnicode(false)
                        .HasColumnType("varchar(10)");

                    b.HasKey("IdCliente")
                        .HasName("PK__Clientes__D5946642560A07B1");

                    b.HasIndex(new[] { "CorreoElectronico" }, "UQ__Clientes__531402F3A819F6C7")
                        .IsUnique();

                    b.ToTable("Clientes");
                });

            modelBuilder.Entity("Proyect.Models.DetalleHabitacione", b =>
                {
                    b.Property<int>("IdDetalleHabitacion")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdDetalleHabitacion"));

                    b.Property<bool>("Estado")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<int>("IdHabitacion")
                        .HasColumnType("int");

                    b.Property<int>("IdReserva")
                        .HasColumnType("int");

                    b.Property<decimal>("Precio")
                        .HasColumnType("decimal(10, 2)");

                    b.HasKey("IdDetalleHabitacion")
                        .HasName("PK__DetalleH__15D58EF948F23CFC");

                    b.HasIndex("IdHabitacion");

                    b.HasIndex("IdReserva");

                    b.ToTable("DetalleHabitaciones");
                });

            modelBuilder.Entity("Proyect.Models.DetallePaquete", b =>
                {
                    b.Property<int>("IdDetallePaquete")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdDetallePaquete"));

                    b.Property<bool>("Estado")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<int>("IdPaquete")
                        .HasColumnType("int");

                    b.Property<int>("IdReserva")
                        .HasColumnType("int");

                    b.Property<decimal>("Precio")
                        .HasColumnType("decimal(10, 2)");

                    b.HasKey("IdDetallePaquete")
                        .HasName("PK__DetalleP__4DD779D7BABEF416");

                    b.HasIndex("IdPaquete");

                    b.HasIndex("IdReserva");

                    b.ToTable("DetallePaquetes");
                });

            modelBuilder.Entity("Proyect.Models.DetalleServicio", b =>
                {
                    b.Property<int>("IdDetalleServicio")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdDetalleServicio"));

                    b.Property<int>("Cantidad")
                        .HasColumnType("int");

                    b.Property<bool>("Estado")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<int>("IdReserva")
                        .HasColumnType("int");

                    b.Property<int>("IdServicio")
                        .HasColumnType("int");

                    b.Property<decimal>("Precio")
                        .HasColumnType("decimal(10, 2)");

                    b.HasKey("IdDetalleServicio")
                        .HasName("PK__DetalleS__0BFF94E69DEE454C");

                    b.HasIndex("IdReserva");

                    b.HasIndex("IdServicio");

                    b.ToTable("DetalleServicios");
                });

            modelBuilder.Entity("Proyect.Models.EstadoReserva", b =>
                {
                    b.Property<int>("IdEstadoReserva")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdEstadoReserva"));

                    b.Property<string>("Descripcion")
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("Estados")
                        .IsRequired()
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)");

                    b.HasKey("IdEstadoReserva")
                        .HasName("PK__EstadoRe__3E654CA85050FB3E");

                    b.ToTable("EstadoReserva", (string)null);
                });

            modelBuilder.Entity("Proyect.Models.HabitacionMueble", b =>
                {
                    b.Property<int>("IdHabitacionMueble")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdHabitacionMueble"));

                    b.Property<int>("Cantidad")
                        .HasColumnType("int");

                    b.Property<int>("IdHabitacion")
                        .HasColumnType("int");

                    b.Property<int>("IdMueble")
                        .HasColumnType("int");

                    b.HasKey("IdHabitacionMueble")
                        .HasName("PK__Habitaci__402E049DD27D6B9C");

                    b.HasIndex("IdHabitacion");

                    b.HasIndex("IdMueble");

                    b.ToTable("HabitacionMueble", (string)null);
                });

            modelBuilder.Entity("Proyect.Models.Habitacione", b =>
                {
                    b.Property<int>("IdHabitacion")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdHabitacion"));

                    b.Property<int>("Cantidad")
                        .HasColumnType("int");

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasMaxLength(255)
                        .IsUnicode(false)
                        .HasColumnType("varchar(255)");

                    b.Property<bool>("Estado")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<int>("IdTipoHabitacion")
                        .HasColumnType("int");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.Property<decimal>("Precio")
                        .HasColumnType("decimal(10, 2)");

                    b.HasKey("IdHabitacion")
                        .HasName("PK__Habitaci__8BBBF9018C946199");

                    b.HasIndex("IdTipoHabitacion");

                    b.ToTable("Habitaciones");
                });

            modelBuilder.Entity("Proyect.Models.MetodoPago", b =>
                {
                    b.Property<int>("IdMetodoPago")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdMetodoPago"));

                    b.Property<bool>("Estado")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.HasKey("IdMetodoPago")
                        .HasName("PK__MetodoPa__6F49A9BECCCBF33A");

                    b.ToTable("MetodoPago", (string)null);
                });

            modelBuilder.Entity("Proyect.Models.Mueble", b =>
                {
                    b.Property<int>("IdMueble")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdMueble"));

                    b.Property<int>("Cantidad")
                        .HasColumnType("int");

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasMaxLength(255)
                        .IsUnicode(false)
                        .HasColumnType("varchar(255)");

                    b.Property<bool>("Estado")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<DateTime>("FechaRegistro")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<int>("IdTipoMueble")
                        .HasColumnType("int");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)");

                    b.HasKey("IdMueble")
                        .HasName("PK__Muebles__829D15E8C1304F0A");

                    b.HasIndex("IdTipoMueble");

                    b.ToTable("Muebles");
                });

            modelBuilder.Entity("Proyect.Models.Paquete", b =>
                {
                    b.Property<int>("IdPaquete")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdPaquete"));

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasMaxLength(255)
                        .IsUnicode(false)
                        .HasColumnType("varchar(255)");

                    b.Property<bool>("Estado")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)");

                    b.Property<decimal>("Precio")
                        .HasColumnType("decimal(10, 2)");

                    b.HasKey("IdPaquete")
                        .HasName("PK__Paquetes__DE278F8B25567580");

                    b.ToTable("Paquetes");
                });

            modelBuilder.Entity("Proyect.Models.PaquetesHabitacione", b =>
                {
                    b.Property<int>("IdPaqueteHabitacion")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdPaqueteHabitacion"));

                    b.Property<int?>("IdHabitacion")
                        .HasColumnType("int");

                    b.Property<int?>("IdPaquete")
                        .HasColumnType("int");

                    b.Property<decimal?>("Precio")
                        .HasColumnType("decimal(10, 2)");

                    b.HasKey("IdPaqueteHabitacion")
                        .HasName("PK__Paquetes__C0EF4AF019115212");

                    b.HasIndex("IdHabitacion");

                    b.HasIndex("IdPaquete");

                    b.ToTable("PaquetesHabitaciones");
                });

            modelBuilder.Entity("Proyect.Models.PaquetesServicio", b =>
                {
                    b.Property<int>("IdPaqueteServicio")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdPaqueteServicio"));

                    b.Property<int?>("IdPaquete")
                        .HasColumnType("int");

                    b.Property<int?>("IdServicio")
                        .HasColumnType("int");

                    b.Property<decimal?>("Precio")
                        .HasColumnType("decimal(10, 2)");

                    b.HasKey("IdPaqueteServicio")
                        .HasName("PK__Paquetes__DE5C2BC22DECE05D");

                    b.HasIndex("IdPaquete");

                    b.HasIndex("IdServicio");

                    b.ToTable("PaquetesServicios");
                });

            modelBuilder.Entity("Proyect.Models.Permiso", b =>
                {
                    b.Property<int>("IdPermiso")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdPermiso"));

                    b.Property<string>("Descripcion")
                        .HasMaxLength(255)
                        .IsUnicode(false)
                        .HasColumnType("varchar(255)");

                    b.Property<string>("NombrePermiso")
                        .IsRequired()
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)");

                    b.HasKey("IdPermiso")
                        .HasName("PK__Permisos__0D626EC81BF47727");

                    b.ToTable("Permisos");
                });

            modelBuilder.Entity("Proyect.Models.Reserva", b =>
                {
                    b.Property<int>("IdReserva")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdReserva"));

                    b.Property<decimal>("Descuento")
                        .HasColumnType("decimal(5, 2)");

                    b.Property<DateTime>("FechaFin")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("FechaInicio")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("FechaReserva")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<int>("IdCliente")
                        .HasColumnType("int");

                    b.Property<int>("IdEstadoReserva")
                        .HasColumnType("int");

                    b.Property<int>("IdMetodoPago")
                        .HasColumnType("int");

                    b.Property<int>("IdPaquete")
                        .HasColumnType("int");

                    b.Property<decimal>("Iva")
                        .HasColumnType("decimal(10, 2)")
                        .HasColumnName("IVA");

                    b.Property<decimal>("Subtotal")
                        .HasColumnType("decimal(10, 2)");

                    b.Property<decimal>("Total")
                        .HasColumnType("decimal(10, 2)");

                    b.Property<int?>("UsuarioIdUsuario")
                        .HasColumnType("int");

                    b.HasKey("IdReserva")
                        .HasName("PK__Reservas__0E49C69D5897E3BE");

                    b.HasIndex("IdCliente");

                    b.HasIndex("IdEstadoReserva");

                    b.HasIndex("IdMetodoPago");

                    b.HasIndex("IdPaquete");

                    b.HasIndex("UsuarioIdUsuario");

                    b.ToTable("Reservas");
                });

            modelBuilder.Entity("Proyect.Models.Role", b =>
                {
                    b.Property<int>("IdRol")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdRol"));

                    b.Property<string>("Descripcion")
                        .HasMaxLength(255)
                        .IsUnicode(false)
                        .HasColumnType("varchar(255)");

                    b.Property<bool>("Estado")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<string>("NombreRol")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.HasKey("IdRol")
                        .HasName("PK__Roles__2A49584C0F208FF6");

                    b.ToTable("Roles");
                });

            modelBuilder.Entity("Proyect.Models.RolesPermiso", b =>
                {
                    b.Property<int>("IdRolPermiso")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdRolPermiso"));

                    b.Property<int?>("IdPermiso")
                        .HasColumnType("int");

                    b.Property<int?>("IdRol")
                        .HasColumnType("int");

                    b.HasKey("IdRolPermiso")
                        .HasName("PK__RolesPer__0CC73B1B6304D448");

                    b.HasIndex("IdPermiso");

                    b.HasIndex("IdRol");

                    b.ToTable("RolesPermisos");
                });

            modelBuilder.Entity("Proyect.Models.Servicio", b =>
                {
                    b.Property<int>("IdServicio")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdServicio"));

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasMaxLength(255)
                        .IsUnicode(false)
                        .HasColumnType("varchar(255)");

                    b.Property<bool>("Estado")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.Property<decimal>("Precio")
                        .HasColumnType("decimal(10, 2)");

                    b.HasKey("IdServicio")
                        .HasName("PK__Servicio__2DCCF9A27DE1C009");

                    b.ToTable("Servicios");
                });

            modelBuilder.Entity("Proyect.Models.TipoHabitacione", b =>
                {
                    b.Property<int>("IdTipoHabitacion")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdTipoHabitacion"));

                    b.Property<int>("Capacidad")
                        .HasColumnType("int");

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasMaxLength(255)
                        .IsUnicode(false)
                        .HasColumnType("varchar(255)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.HasKey("IdTipoHabitacion")
                        .HasName("PK__TipoHabi__AB75E87CF22C5C7B");

                    b.ToTable("TipoHabitaciones");
                });

            modelBuilder.Entity("Proyect.Models.TipoMueble", b =>
                {
                    b.Property<int>("IdTipoMueble")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdTipoMueble"));

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasMaxLength(255)
                        .IsUnicode(false)
                        .HasColumnType("varchar(255)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.HasKey("IdTipoMueble")
                        .HasName("PK__TipoMueb__C451A954F856429B");

                    b.ToTable("TipoMueble", (string)null);
                });

            modelBuilder.Entity("Proyect.Models.Usuario", b =>
                {
                    b.Property<int>("IdUsuario")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdUsuario"));

                    b.Property<string>("Apellido")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("Celular")
                        .HasMaxLength(15)
                        .IsUnicode(false)
                        .HasColumnType("varchar(15)");

                    b.Property<string>("CodigoRestablecimiento")
                        .HasMaxLength(200)
                        .IsUnicode(false)
                        .HasColumnType("varchar(200)");

                    b.Property<string>("Contraseña")
                        .HasMaxLength(30)
                        .IsUnicode(false)
                        .HasColumnType("varchar(30)");

                    b.Property<string>("CorreoElectronico")
                        .IsRequired()
                        .HasMaxLength(150)
                        .IsUnicode(false)
                        .HasColumnType("varchar(150)");

                    b.Property<string>("Direccion")
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("Documento")
                        .IsRequired()
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)");

                    b.Property<bool>("Estado")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<DateTime?>("FechaCreacion")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<int>("IdRol")
                        .HasColumnType("int");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("TipoDocumento")
                        .IsRequired()
                        .HasMaxLength(10)
                        .IsUnicode(false)
                        .HasColumnType("varchar(10)");

                    b.HasKey("IdUsuario")
                        .HasName("PK__Usuarios__5B65BF9703073B92");

                    b.HasIndex("IdRol");

                    b.HasIndex(new[] { "CorreoElectronico" }, "UQ__Usuarios__531402F36AFB6096")
                        .IsUnique();

                    b.ToTable("Usuarios");
                });

            modelBuilder.Entity("Proyect.Models.Abono", b =>
                {
                    b.HasOne("Proyect.Models.Reserva", "IdReservaNavigation")
                        .WithMany("Abonos")
                        .HasForeignKey("IdReserva")
                        .IsRequired()
                        .HasConstraintName("FK__Abonos__IdReserv__76969D2E");

                    b.Navigation("IdReservaNavigation");
                });

            modelBuilder.Entity("Proyect.Models.DetalleHabitacione", b =>
                {
                    b.HasOne("Proyect.Models.Habitacione", "IdHabitacionNavigation")
                        .WithMany("DetalleHabitaciones")
                        .HasForeignKey("IdHabitacion")
                        .IsRequired()
                        .HasConstraintName("FK__DetalleHa__IdHab__03F0984C");

                    b.HasOne("Proyect.Models.Reserva", "IdReservaNavigation")
                        .WithMany("DetalleHabitaciones")
                        .HasForeignKey("IdReserva")
                        .IsRequired()
                        .HasConstraintName("FK__DetalleHa__IdRes__02FC7413");

                    b.Navigation("IdHabitacionNavigation");

                    b.Navigation("IdReservaNavigation");
                });

            modelBuilder.Entity("Proyect.Models.DetallePaquete", b =>
                {
                    b.HasOne("Proyect.Models.Paquete", "IdPaqueteNavigation")
                        .WithMany("DetallePaquetes")
                        .HasForeignKey("IdPaquete")
                        .IsRequired()
                        .HasConstraintName("FK__DetallePa__IdPaq__7F2BE32F");

                    b.HasOne("Proyect.Models.Reserva", "IdReservaNavigation")
                        .WithMany("DetallePaquetes")
                        .HasForeignKey("IdReserva")
                        .IsRequired()
                        .HasConstraintName("FK__DetallePa__IdRes__7E37BEF6");

                    b.Navigation("IdPaqueteNavigation");

                    b.Navigation("IdReservaNavigation");
                });

            modelBuilder.Entity("Proyect.Models.DetalleServicio", b =>
                {
                    b.HasOne("Proyect.Models.Reserva", "IdReservaNavigation")
                        .WithMany("DetalleServicios")
                        .HasForeignKey("IdReserva")
                        .IsRequired()
                        .HasConstraintName("FK__DetalleSe__IdRes__797309D9");

                    b.HasOne("Proyect.Models.Servicio", "IdServicioNavigation")
                        .WithMany("DetalleServicios")
                        .HasForeignKey("IdServicio")
                        .IsRequired()
                        .HasConstraintName("FK__DetalleSe__IdSer__7A672E12");

                    b.Navigation("IdReservaNavigation");

                    b.Navigation("IdServicioNavigation");
                });

            modelBuilder.Entity("Proyect.Models.HabitacionMueble", b =>
                {
                    b.HasOne("Proyect.Models.Habitacione", "IdHabitacionNavigation")
                        .WithMany("HabitacionMuebles")
                        .HasForeignKey("IdHabitacion")
                        .IsRequired()
                        .HasConstraintName("FK__Habitacio__IdHab__5629CD9C");

                    b.HasOne("Proyect.Models.Mueble", "IdMuebleNavigation")
                        .WithMany("HabitacionMuebles")
                        .HasForeignKey("IdMueble")
                        .IsRequired()
                        .HasConstraintName("FK__Habitacio__IdMue__571DF1D5");

                    b.Navigation("IdHabitacionNavigation");

                    b.Navigation("IdMuebleNavigation");
                });

            modelBuilder.Entity("Proyect.Models.Habitacione", b =>
                {
                    b.HasOne("Proyect.Models.TipoHabitacione", "IdTipoHabitacionNavigation")
                        .WithMany("Habitaciones")
                        .HasForeignKey("IdTipoHabitacion")
                        .IsRequired()
                        .HasConstraintName("FK__Habitacio__IdTip__534D60F1");

                    b.Navigation("IdTipoHabitacionNavigation");
                });

            modelBuilder.Entity("Proyect.Models.Mueble", b =>
                {
                    b.HasOne("Proyect.Models.TipoMueble", "IdTipoMuebleNavigation")
                        .WithMany("Muebles")
                        .HasForeignKey("IdTipoMueble")
                        .IsRequired()
                        .HasConstraintName("FK__Muebles__IdTipoM__4D94879B");

                    b.Navigation("IdTipoMuebleNavigation");
                });

            modelBuilder.Entity("Proyect.Models.PaquetesHabitacione", b =>
                {
                    b.HasOne("Proyect.Models.Habitacione", "IdHabitacionNavigation")
                        .WithMany("PaquetesHabitaciones")
                        .HasForeignKey("IdHabitacion")
                        .HasConstraintName("FK__PaquetesH__IdHab__60A75C0F");

                    b.HasOne("Proyect.Models.Paquete", "IdPaqueteNavigation")
                        .WithMany("PaquetesHabitaciones")
                        .HasForeignKey("IdPaquete")
                        .HasConstraintName("FK__PaquetesH__IdPaq__5FB337D6");

                    b.Navigation("IdHabitacionNavigation");

                    b.Navigation("IdPaqueteNavigation");
                });

            modelBuilder.Entity("Proyect.Models.PaquetesServicio", b =>
                {
                    b.HasOne("Proyect.Models.Paquete", "IdPaqueteNavigation")
                        .WithMany("PaquetesServicios")
                        .HasForeignKey("IdPaquete")
                        .HasConstraintName("FK__PaquetesS__IdPaq__6383C8BA");

                    b.HasOne("Proyect.Models.Servicio", "IdServicioNavigation")
                        .WithMany("PaquetesServicios")
                        .HasForeignKey("IdServicio")
                        .HasConstraintName("FK__PaquetesS__IdSer__6477ECF3");

                    b.Navigation("IdPaqueteNavigation");

                    b.Navigation("IdServicioNavigation");
                });

            modelBuilder.Entity("Proyect.Models.Reserva", b =>
                {
                    b.HasOne("Proyect.Models.Cliente", "IdClienteNavigation")
                        .WithMany("Reservas")
                        .HasForeignKey("IdCliente")
                        .IsRequired()
                        .HasConstraintName("FK__Reservas__IdClie__6D0D32F4");

                    b.HasOne("Proyect.Models.EstadoReserva", "IdEstadoReservaNavigation")
                        .WithMany("Reservas")
                        .HasForeignKey("IdEstadoReserva")
                        .IsRequired()
                        .HasConstraintName("FK__Reservas__IdEsta__6FE99F9F");

                    b.HasOne("Proyect.Models.MetodoPago", "IdMetodoPagoNavigation")
                        .WithMany("Reservas")
                        .HasForeignKey("IdMetodoPago")
                        .IsRequired()
                        .HasConstraintName("FK__Reservas__IdMeto__70DDC3D8");

                    b.HasOne("Proyect.Models.Paquete", "IdPaqueteNavigation")
                        .WithMany("Reservas")
                        .HasForeignKey("IdPaquete")
                        .IsRequired()
                        .HasConstraintName("FK__Reservas__IdPaqu__6EF57B66");

                    b.HasOne("Proyect.Models.Usuario", null)
                        .WithMany("Reservas")
                        .HasForeignKey("UsuarioIdUsuario");

                    b.Navigation("IdClienteNavigation");

                    b.Navigation("IdEstadoReservaNavigation");

                    b.Navigation("IdMetodoPagoNavigation");

                    b.Navigation("IdPaqueteNavigation");
                });

            modelBuilder.Entity("Proyect.Models.RolesPermiso", b =>
                {
                    b.HasOne("Proyect.Models.Permiso", "IdPermisoNavigation")
                        .WithMany("RolesPermisos")
                        .HasForeignKey("IdPermiso")
                        .HasConstraintName("FK__RolesPerm__IdPer__3D5E1FD2");

                    b.HasOne("Proyect.Models.Role", "IdRolNavigation")
                        .WithMany("RolesPermisos")
                        .HasForeignKey("IdRol")
                        .HasConstraintName("FK__RolesPerm__IdRol__3C69FB99");

                    b.Navigation("IdPermisoNavigation");

                    b.Navigation("IdRolNavigation");
                });

            modelBuilder.Entity("Proyect.Models.Usuario", b =>
                {
                    b.HasOne("Proyect.Models.Role", "IdRolNavigation")
                        .WithMany("Usuarios")
                        .HasForeignKey("IdRol")
                        .IsRequired()
                        .HasConstraintName("FK__Usuarios__IdRol__4316F928");

                    b.Navigation("IdRolNavigation");
                });

            modelBuilder.Entity("Proyect.Models.Cliente", b =>
                {
                    b.Navigation("Reservas");
                });

            modelBuilder.Entity("Proyect.Models.EstadoReserva", b =>
                {
                    b.Navigation("Reservas");
                });

            modelBuilder.Entity("Proyect.Models.Habitacione", b =>
                {
                    b.Navigation("DetalleHabitaciones");

                    b.Navigation("HabitacionMuebles");

                    b.Navigation("PaquetesHabitaciones");
                });

            modelBuilder.Entity("Proyect.Models.MetodoPago", b =>
                {
                    b.Navigation("Reservas");
                });

            modelBuilder.Entity("Proyect.Models.Mueble", b =>
                {
                    b.Navigation("HabitacionMuebles");
                });

            modelBuilder.Entity("Proyect.Models.Paquete", b =>
                {
                    b.Navigation("DetallePaquetes");

                    b.Navigation("PaquetesHabitaciones");

                    b.Navigation("PaquetesServicios");

                    b.Navigation("Reservas");
                });

            modelBuilder.Entity("Proyect.Models.Permiso", b =>
                {
                    b.Navigation("RolesPermisos");
                });

            modelBuilder.Entity("Proyect.Models.Reserva", b =>
                {
                    b.Navigation("Abonos");

                    b.Navigation("DetalleHabitaciones");

                    b.Navigation("DetallePaquetes");

                    b.Navigation("DetalleServicios");
                });

            modelBuilder.Entity("Proyect.Models.Role", b =>
                {
                    b.Navigation("RolesPermisos");

                    b.Navigation("Usuarios");
                });

            modelBuilder.Entity("Proyect.Models.Servicio", b =>
                {
                    b.Navigation("DetalleServicios");

                    b.Navigation("PaquetesServicios");
                });

            modelBuilder.Entity("Proyect.Models.TipoHabitacione", b =>
                {
                    b.Navigation("Habitaciones");
                });

            modelBuilder.Entity("Proyect.Models.TipoMueble", b =>
                {
                    b.Navigation("Muebles");
                });

            modelBuilder.Entity("Proyect.Models.Usuario", b =>
                {
                    b.Navigation("Reservas");
                });
#pragma warning restore 612, 618
        }
    }
}
